; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_custom]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
board_build.flash_size = 4MB
board_build.psram = enabled
upload_speed = 921600
monitor_speed = 115200
build_flags = 
	-D EVE_BT816
	-D EVE_CS=47
	-D EVE_PDN=45
	-D EVE_RIVERDI_RVT43ALBNWN00
	-D EVE_HSIZE=480
	-D EVE_VSIZE=272
	-D EVE_HSYNC0=0
	-D EVE_HSYNC1=41
	-D EVE_HOFFSET=43
	-D EVE_HCYCLE=548
	-D EVE_VSYNC0=0
	-D EVE_VSYNC1=10
	-D EVE_VOFFSET=12
	-D EVE_VCYCLE=292
	-D EVE_PCLK=5
	-D EVE_SWIZZLE=0
	-D EVE_PCLKPOL=1
	-D EVE_CSPREAD=1
	-D EVE_DITHER=1
	-DARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	dennis-ard/Arducam_Mega@^2.0.9
	bblanchon/ArduinoJson@^7.2.2
	https://github.com/RudolphRiedel/FT800-FT813.git
	madhephaestus/ESP32Servo@^3.2.0
