; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_custom]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
board_build.flash_size = 4MB
board_build.psram = enabled
upload_speed = 921600
monitor_speed = 115200
#monitor_port = COM7

lib_deps =
    https://github.com/RudolphRiedel/FT800-FT813.git

build_flags =
    -D EVE_BT816          ; tells the library you have a BT816 chip
    -D EVE_CS=47          ; your CS pin
    -D EVE_PDN=45         ; power-down pin
    -D EVE_RIVERDI_RVT43ALBNWN00  ; RVT43ALBNWN00 display module
    -D EVE_HSIZE=480      ; display width
    -D EVE_VSIZE=272      ; display height
    -D EVE_HSYNC0=0       ; horizontal sync start
    -D EVE_HSYNC1=41      ; horizontal sync end
    -D EVE_HOFFSET=43     ; horizontal offset
    -D EVE_HCYCLE=548     ; horizontal cycle
    -D EVE_VSYNC0=0       ; vertical sync start
    -D EVE_VSYNC1=10      ; vertical sync end
    -D EVE_VOFFSET=12     ; vertical offset
    -D EVE_VCYCLE=292     ; vertical cycle
    -D EVE_PCLK=5         ; pixel clock divider
    -D EVE_SWIZZLE=0      ; output pin order
    -D EVE_PCLKPOL=1      ; pixel clock polarity
    -D EVE_CSPREAD=1      ; reduce noise
    -D EVE_DITHER=1       ; dithering
    -DARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1